version: "2"

services:
  server:
    build: ./server
    image: scrooloose/chesticles_server
    command: "nodemon ./bin/www"
    volumes:
      - ./server:/app

    ports:
      - "5001:3000"

  client:
    build: ./client
    image: scrooloose/chesticles_client
    command: "npm start"
    volumes:
      - ./client:/app

    ports:
      - "5000:3000"

    env_file:
      - ./client/env
